sudo: false
language: go
os:
- linux
- osx
before_install:
- openssl aes-256-cbc -K $encrypted_76a464c5f1b5_key -iv $encrypted_76a464c5f1b5_iv
  -in gc.enc -out ~/.gitcookies -d
- export $(./git-commit.sh | tr ' ' =)
env:
- CGO_ENABLED=0 GO111MODULE=on
go:
- 1.11.x
before_script:
- go get ${gobuild_args} ./...
script:
- go build ${gobuild_args}
- go test -v ./...
gobuild_args: -a -ldflags "-extldflags '-static' -X github.com/buchgr/bazel-remote/server.GitCommit=${STABLE_GIT_COMMIT}"
  .
before_deploy:
- export TAG=$(git describe --tags)
- export S=$(uname -s | tr A-Z a-z)
- export M=$(uname -m)
- cp bazel-remote bazel-remote-${TAG}-${S}-${M}
- |
  if [[ $(uname -s) == Darwin ]]; then
    shasum -a 256 bazel-remote-${TAG}-${S}-${M} > bazel-remote-${TAG}-${S}-${M}.sha256
  else
    sha256sum bazel-remote-${TAG}-${S}-${M} > bazel-remote-${TAG}-${S}-${M}.sha256
  fi
deploy:
  provider: releases
  api_key:
    secure: m+IM8AHuJD7UPaCDFTb6byD9pdTvMFwr1xc0A1knZFCeCP1ViMRH0HwDoqii5GxZ4GaBtmjB5x5eRtKMmPDpmxp2xeeOF+ELN8IB2TUA+ez4X7y5cgsMYfX/u3Shu2pMKZPoI0ny15BBaY0xrfC/+J3ZDOyZBVA3bs9t6kH1B23EygBT5g5KYweYK9MtRSrSZTVHvwSjLdbR+9MGmgXishzXxMQbmMgPNYiHToS48f0Fh+CUrRC+ZHEn+8IZOGrDXbhDGFnlk48LbK8zvMaUNiM7UXF4fwkZM5rPd7tTWd51zKO2t7oDFSxGHaIdqC2Kf2kKtq+Scf27F3+Cx4g2oO2JNwFSrsKWND+MP6ryk4TRwRVhVHHLAgpWsHBVORzF/0/aVAHcSEE8pENVze1hT529w+iSJJa49Sj5FUhz0Mf6Thcql5GiXUGDLs7nNm9GCOlf0WuHqE3IhpDPucLq3XRPNOukc+c6kAB7KG6MDx/531nmUKZmyr2o7ajzWxxBCfaslmnb2Ce/MpAu41lZNVi4g2xvbGr1VC3C6Yi55EwMgT8MtbK17txcd2E8dOhDIkRcslaGpLtaaJw8FpOMsrOYiVxOYdPkNyVX39gXP61NcyiFAjdQqE/pMmajdazwHLnhpCQ+M+n1sgylujfICCJNuGeDhlojb/MU4S7lSsk=
  file: bazel-remote-*
  file_glob: true
  skip_cleanup: true
  draft: true
  on:
    repo: ob/bazel-remote
    tags: true
